Algoritmo "salario final"
VAR
dinheiro,dol,marco_ale,libra :REAL
Inicio
ESCREVA ("DIGITE A QUANTIDADE DE DINHEIRO QUE POSSUI: R$")
LEIA (dinheiro)
dol <- dinheiro / 1.8
marco_ale <- dinheiro / 2.0
libra <- dinheiro / 3.57
ESCREVA ("A CONVERSAO PARA DÓLAR É DE:", dol)
LEIA (dol)
ESCREVA ("A CONVERSAO PARA MARCO ALEMÃO É DE: ", marco_ale)
LEIA (marco_ale)
ESCREVA ("A CONVERSAO PARA LIBRAS É DE:", libra)
LEIA (libra)

Fimalgoritmo